Jb backgrnd img
Aman-codde/js-netflix-clone pull request #3
Opened 2024-09-16 15:18 UTC by jothiaishu

2024-09-16 15:45 UTC, Aman-codde commented on header-image.png
The image should be added in images folder

2024-09-16 15:46 UTC, Aman-codde requested changes
Please make the changes for image

2024-09-16 22:34 UTC, jothiaishu commented on header-image.png
okay

2024-09-17 00:05 UTC, jothiaishu reviewed
ok ill add in the image folder

2024-09-17 04:47 UTC, closed without merging